const defaults={points:2480,purchased:[],completedCompetitions:[],products:[
{id:1,name:"قسيمة مكتبة",description:"قسيمة لشراء كتاب من المكتبة",price:1200,icon:"📚",stock:8},
{id:2,name:"كوب الإنجاز",description:"كوب حصري يحمل شعار المنصة",price:1800,icon:"🏆",stock:4},
{id:3,name:"ساعة ذكية",description:"جائزة للمثابرين وأصحاب الهمم",price:6500,icon:"⌚",stock:2},
{id:4,name:"حقيبة صيف",description:"حقيبة مرحة للدراسة والمغامرات",price:3200,icon:"🎒",stock:6},
{id:5,name:"وقت لعب إضافي",description:"30 دقيقة ألعاب تعليمية إضافية",price:600,icon:"🎮",stock:20},
{id:6,name:"شارة المستكشف",description:"شارة نادرة تظهر في ملفك الشخصي",price:900,icon:"🧭",stock:12}],
posts:[{id:1,author:"إدارة صيف",role:"الإدارة",time:"منذ ساعتين",text:"انطلقت مسابقة شمس المعرفة! أكملوا المرحلة الأولى قبل مساء الخميس لتحصلوا على 250 نجمة إضافية.",likes:28},{id:2,author:"الأستاذة نورة",role:"معلمة العلوم",time:"أمس",text:"فخورة جدًا بإنجازات هذا الأسبوع. ثلاثة مغامرين وصلوا إلى جزيرة العلوم، من سيكون التالي؟",likes:41}]};
let authData={users:[],requests:[]};
let currentUser=null;
let state=loadState();
const titles={home:["مرحبًا بك","جاهز لمغامرة صيفية؟"],achievements:["يوم جديد وإنجاز جديد","إنجازاتي اليومية"],journey:["مغامرتك تكبر","خريطة كنز الإنجاز"],competitions:["نافس أصدقاءك","تحديات الشمس"],episodes:["شاهد واكتشف","حكايات صيف"],games:["بوابة المغامرة اليومية","ساحة التحديات"],store:["حوّل نجومك إلى مفاجآت","دكان النجوم"],posts:["أصدقاء صيف","المنشورات والأخبار"],owner:["إدارة النظام","لوحة مالك صيف"]};
const competitions=[
{id:1,title:"عباقرة العلوم",desc:"اختبر معرفتك في الفضاء والطاقة وجسم الإنسان.",reward:350,icon:"⚗",color:"visual-teal",tag:"الأكثر مشاركة"},
{id:2,title:"سيد الكلمات",desc:"سباق لغوي ممتع في المفردات والإملاء.",reward:280,icon:"أ",color:"visual-coral",tag:"ينتهي خلال يومين"},
{id:3,title:"تحدي الحساب",desc:"حل المسائل السريعة وتصدر قائمة الأسبوع.",reward:400,icon:"∞",color:"visual-blue",tag:"جديد"},
{id:4,title:"ذاكرة التاريخ",desc:"رتّب الأحداث واكتشف شخصيات صنعت الفرق.",reward:300,icon:"⌛",color:"visual-gold",tag:"متوسط"},
{id:5,title:"قارئ الشهر",desc:"اقرأ الملخص ثم أجب عن أسئلة الفهم.",reward:500,icon:"📖",color:"visual-teal",tag:"مميز"},
{id:6,title:"المخترع الصغير",desc:"صمم فكرة مبتكرة وقدّمها بأسلوبك.",reward:650,icon:"⚙",color:"visual-coral",tag:"فريق جماعي"}];
const episodes=[["مختبر الدهشة","لماذا يتغير لون السماء؟","12 دقيقة","⚗","visual-blue"],["حكاية رقم","سر الرقم صفر","9 دقائق","0","visual-gold"],["لغتنا الجميلة","رحلة الكلمة العربية","15 دقيقة","ض","visual-coral"],["كوكبنا","حياة مذهلة تحت الماء","18 دقيقة","◉","visual-teal"],["صنّاع المستقبل","كيف يعمل الروبوت؟","14 دقيقة","⚙","visual-blue"],["من التاريخ","قصة بيت الحكمة","11 دقيقة","⌛","visual-gold"]];
const games=[["مملكة الكلمات","كوّن أكبر عدد من الكلمات قبل انتهاء الوقت.","🔤","visual-coral",80],["صائد الأرقام","التقط الإجابة الصحيحة وتجاوز العقبات.","🎯","visual-blue",100],["ذاكرة الكواكب","طابق الكواكب مع معلوماتها المدهشة.","🪐","visual-teal",120],["مهندس الجسور","استخدم المنطق لبناء جسر متوازن.","🏗","visual-gold",150]];

function loadState(){try{const stored=JSON.parse(localStorage.getItem("ofoq-state"));return{...defaults,...stored,products:stored?.products||defaults.products,posts:stored?.posts||defaults.posts}}catch{return structuredClone(defaults)}}
function saveState(){localStorage.setItem("ofoq-state",JSON.stringify(state));updatePoints()}
function updatePoints(){document.querySelector("#headerPoints").textContent=state.points.toLocaleString("ar-SA")}
const rewardCategoryLabels={daily:"جوائز يومية",weekly:"جوائز أسبوعية",grand:"جوائز كبرى"};
const achievementCategories={golden_achievements:{name:"الإنجازات الذهبية",icon:"✨",text:"العبادات اليومية"},golden_fortress:{name:"الحصن الذهبي",icon:"🛡️",text:"الأذكار والأوراد اليومية"},noori:{name:"نوري",icon:"📖",text:"ورد القرآن الكريم"},knowledge_station:{name:"محطة المعرفة",icon:"💡",text:"الثقافة والمعرفة"},golden_minute:{name:"الدقيقة الذهبية",icon:"⏱️",text:"المقاطع المفيدة"},health_first:{name:"صحتي أولاً",icon:"🌿",text:"العادات الصحية"}};
let selectedAchievementDate="";
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function formatRewardPoints(value){return Number(value||0).toLocaleString("ar-SA")+" نقطة"}
function rewardSections(){return Object.entries(rewardCategoryLabels).map(([category,label])=>{const rewards=(state.rewards||[]).filter(item=>item.category===category);return`<section class="reward-section reward-${category}"><div class="reward-section-head"><div><span>${category==="daily"?"☀":"weekly"===category?"📅":"🏆"}</span><h3>${label}</h3></div><small>${rewards.length} جوائز</small></div>${rewards.length?`<div class="reward-grid">${rewards.map(item=>{const canBuy=currentUser?.role==="student"&&state.points>=Number(item.amount);return`<article class="reward-card"><img src="${item.image}" alt="${escapeHtml(item.name)}"><div class="reward-card-info"><h4>${escapeHtml(item.name)}</h4><strong>${formatRewardPoints(item.amount)}</strong><button class="reward-buy-button" ${canBuy?"":"disabled"} onclick="buyReward(${item.id})">${canBuy?"شراء الجائزة":"الرصيد غير كافٍ"}</button></div></article>`}).join("")}</div>`:`<div class="empty-state">ستظهر الجوائز الجديدة هنا قريبًا</div>`}</section>`}).join("")}
function navigate(page){if(page==="owner"&&currentUser?.role!=="owner")return showToast("هذه الصفحة مخصصة لمالك المنصة");document.querySelectorAll(".page").forEach(el=>el.classList.remove("active"));document.querySelectorAll(".nav-item").forEach(el=>el.classList.toggle("active",el.dataset.page===page));document.querySelector(`#${page}Page`).classList.add("active");document.querySelector(".page-title .eyebrow").textContent=page==="home"?`مرحبًا يا ${currentUser?.name||"مستفيد"}`:titles[page][0];document.querySelector("#pageTitle").textContent=titles[page][1];document.querySelector("#sidebar").classList.remove("open");renderPage(page);window.scrollTo({top:0,behavior:"smooth"})}

function switchAuthView(view){document.querySelectorAll(".auth-tab").forEach(tab=>tab.classList.toggle("active",tab.dataset.authView===view));document.querySelector("#loginForm").classList.toggle("hidden",view!=="login");document.querySelector("#requestForm").classList.toggle("hidden",view!=="request");document.querySelector("#authTitle").textContent=view==="login"?"تسجيل الدخول":"طلب حساب جديد";document.querySelector("#authSubtitle").textContent=view==="login"?"أدخل بيانات حسابك للوصول إلى المنصة":"أرسل بياناتك ليعتمدها مالك المنصة"}
async function api(path,options={}){const response=await fetch(`/api/${path}`,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||"تعذر الاتصال بالخادم");error.status=response.status;throw error}return data}
async function login(username,password){const data=await api("auth/login",{method:"POST",body:JSON.stringify({username,password})});currentUser=data.user;showApp()}
function showApp(){document.querySelector("#authScreen").classList.add("hidden");document.querySelector("#appShell").classList.remove("hidden");const isOwner=currentUser.role==="owner";document.querySelector(".owner-entry").classList.toggle("hidden",!isOwner);document.querySelector(".points-pill").classList.toggle("hidden",isOwner);document.querySelector("#sidebarName").textContent=currentUser.name;document.querySelector("#sidebarRole").textContent=isOwner?"مالك المنصة":`المستوى ${currentUser.level||1}`;const initial=currentUser.name.trim()[0]||"م";document.querySelector("#sidebarAvatar").textContent=initial;document.querySelector("#topAvatar").textContent=initial;document.querySelector("#pageGreeting").textContent=`مرحبًا يا ${currentUser.name}`;if(!isOwner)state.points=Number(currentUser.points||0);updatePoints();navigate(isOwner?"owner":"home")}
async function logout(){try{await api("auth/logout",{method:"POST"})}catch{}currentUser=null;document.querySelector("#appShell").classList.add("hidden");document.querySelector("#authScreen").classList.remove("hidden");document.querySelector("#loginForm").reset();switchAuthView("login")}
async function submitRegistration(){const message=document.querySelector("#requestMessage");message.classList.remove("success");try{await api("registration-requests",{method:"POST",body:JSON.stringify({name:document.querySelector("#requestName").value.trim(),username:document.querySelector("#requestUsername").value.trim(),contact:document.querySelector("#requestContact").value.trim(),note:document.querySelector("#requestNote").value.trim()})});document.querySelector("#requestForm").reset();message.textContent="تم إرسال طلبك، ستتمكن من الدخول بعد موافقة المالك";message.classList.add("success")}catch(error){message.textContent=error.message}}
function pageBanner(title,text,action=""){return`<div class="page-banner"><div><h2>${title}</h2><p>${text}</p></div>${action}</div>`}
function renderPage(page){if(page==="achievements")renderAchievements();if(page==="journey")renderJourney();if(page==="competitions")renderCompetitions();if(page==="episodes")renderEpisodes();if(page==="games")renderGames();if(page==="store")renderStore();if(page==="posts")renderPosts();if(page==="owner")renderOwner()}

function achievementDateLabel(date,today){if(date===today)return"اليوم";return new Date(`${date}T12:00:00`).toLocaleDateString("ar-SA",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}
function moveAchievementDate(days){const value=new Date(`${selectedAchievementDate}T12:00:00`);value.setDate(value.getDate()+days);selectedAchievementDate=value.toISOString().slice(0,10);renderAchievements()}
async function renderAchievements(){const page=document.querySelector("#achievementsPage");page.innerHTML=`<div class="loading-state">جارٍ تحميل إنجازاتك...</div>`;try{const query=selectedAchievementDate?`?date=${selectedAchievementDate}`:"";const data=await api(`achievements${query}`);selectedAchievementDate=data.date;const grouped=Object.keys(achievementCategories).map(category=>{const info=achievementCategories[category],tasks=data.tasks.filter(task=>task.category===category);return`<section class="achievement-category"><div class="achievement-category-head"><span>${info.icon}</span><div><h3>${info.name}</h3><p>${info.text}</p></div><b>${tasks.filter(task=>task.completed).length}/${tasks.length}</b></div>${tasks.length?`<div class="achievement-list">${tasks.map(task=>`<button class="achievement-task ${task.completed?"completed":""}" ${task.completed||currentUser?.role!=="student"?"disabled":""} onclick="completeAchievementTask(${task.id})"><span class="achievement-check">${task.completed?"✓":""}</span><span><strong>${escapeHtml(task.title)}</strong>${task.description?`<small>${escapeHtml(task.description)}</small>`:""}</span><b>+${Number(task.points).toLocaleString("ar-SA")} ★</b></button>`).join("")}</div>`:`<div class="achievement-empty">لم يضف المالك مهامًا في هذا القسم بعد</div>`}</section>`}).join("");const earned=data.summary.badges.filter(badge=>badge.earned).length;page.innerHTML=`${pageBanner("إنجازات تتجدد كل يوم","ضع علامة عند إتمام المهمة، ويمكنك الرجوع للأيام السابقة واستدراك ما فاتك.")}<div class="achievement-date-bar"><button class="date-arrow" onclick="moveAchievementDate(-1)">اليوم السابق</button><div><small>إنجازات</small><strong>${achievementDateLabel(data.date,data.today)}</strong><input type="date" value="${data.date}" max="${data.today}" onchange="selectedAchievementDate=this.value;renderAchievements()"></div><button class="date-arrow" onclick="moveAchievementDate(1)" ${data.date>=data.today?"disabled":""}>اليوم التالي</button></div><div class="achievement-summary"><div><span>⭐</span><strong>${data.summary.points.toLocaleString("ar-SA")}</strong><small>نقاط الإنجازات</small></div><div><span>✅</span><strong>${data.summary.completedCount.toLocaleString("ar-SA")}</strong><small>مهمة مكتملة</small></div><div><span>🏅</span><strong>${earned}/${data.summary.badges.length}</strong><small>أوسمة مكتسبة</small></div></div><div class="achievement-grid">${grouped}</div><section class="achievement-badges"><div class="section-heading"><div><span class="eyebrow">تتقدم مع كل إنجاز</span><h2>أوسمتي</h2></div></div><div class="badges-row">${data.summary.badges.map(badge=>`<article class="achievement-badge ${badge.earned?"earned":"locked"}"><span>${badge.icon}</span><strong>${badge.name}</strong><small>${badge.earned?"تم الحصول عليه":`${badge.threshold} نقطة`}</small></article>`).join("")}</div></section>`}catch(error){page.innerHTML=`<div class="empty-state">${escapeHtml(error.message)}</div>`}}
async function completeAchievementTask(id){try{const result=await api(`achievements/${id}/complete`,{method:"POST",body:JSON.stringify({date:selectedAchievementDate})});state.points=result.points;currentUser.points=result.points;updatePoints();await renderAchievements();showToast(`أحسنت! أضفنا ${result.awarded} نقطة إلى رصيدك`)}catch(error){showToast(error.message)}}

function renderJourney(){document.querySelector("#journeyPage").innerHTML=`
${pageBanner("رحلتك تنمو مع كل إنجاز","أكمل الأنشطة لتفتح مناطق جديدة وتجمع الشارات والنقاط.")}
<div class="stat-grid"><div class="stat-card"><strong>68%</strong><span>نسبة إكمال الرحلة</span></div><div class="stat-card"><strong>${state.points.toLocaleString("ar-SA")}</strong><span>إجمالي نقاطك</span></div><div class="stat-card"><strong>18</strong><span>مهمة مكتملة</span></div><div class="stat-card"><strong>6</strong><span>شارات مكتسبة</span></div></div>
<section class="journey-preview journey-full"><img src="assets/learning-world.png" alt="خريطة رحلة الطالب"><div class="map-overlay"></div>
<button class="stage-marker stage-1 completed" onclick="showStage(1)"><span>✓</span><b>بداية الرحلة</b></button><button class="stage-marker stage-2 completed" onclick="showStage(2)"><span>✓</span><b>حديقة المعرفة</b></button><button class="stage-marker stage-3 current" onclick="showStage(3)"><span>3</span><b>مرصد العلوم</b></button><button class="stage-marker stage-4 locked" onclick="showStage(4)"><span>🔒</span><b>جزيرة الإبداع</b></button></section>`}

async function renderCompetitions(){try{const data=await api("competition-settings");data.settings.forEach(setting=>{const item=competitions.find(comp=>comp.id===Number(setting.competition_id));if(item)item.reward=Number(setting.points)})}catch(error){showToast(error.message)}document.querySelector("#competitionsPage").innerHTML=`
${pageBanner("تحديات تصنع الفرق","شارك، اجمع النقاط، وشاهد اسمك في قائمة المتصدرين.")}
<div class="filter-row"><button class="filter-button active">الكل</button><button class="filter-button">فردية</button><button class="filter-button">جماعية</button><button class="filter-button">مكتملة</button></div>
<div class="content-grid">${competitions.map(item=>`<article class="content-card"><div class="card-visual ${item.color}"><span class="tag">${item.tag}</span>${item.icon}</div><div class="card-body"><h3>${item.title}</h3><p>${item.desc}</p><div class="card-meta"><span>المكافأة: <b>${item.reward} ★</b></span><button class="card-action" onclick="openCompetition(${item.id})">${state.completedCompetitions.includes(item.id)?"مكتملة ✓":"ابدأ الآن ←"}</button></div></div></article>`).join("")}</div>`}

function renderEpisodes(){document.querySelector("#episodesPage").innerHTML=`
${pageBanner("برامج وحلقات مختارة لك","شاهد حلقات قصيرة، ثم أجب عن سؤال لتحصل على النقاط.")}
<div class="filter-row"><button class="filter-button active">أحدث الحلقات</button><button class="filter-button">العلوم</button><button class="filter-button">اللغة</button><button class="filter-button">التاريخ</button></div>
<div class="content-grid">${episodes.map((e,i)=>`<article class="content-card"><div class="card-visual ${e[4]}">${e[3]}<span class="tag">الحلقة ${i+1}</span></div><div class="card-body"><small>${e[0]}</small><h3>${e[1]}</h3><div class="card-meta"><span>▶ ${e[2]}</span><button class="card-action" onclick="playEpisode(${i})">شاهد الآن ←</button></div></div></article>`).join("")}</div>`}

function renderGames(){document.querySelector("#gamesPage").innerHTML=`
${pageBanner("العب، فكّر، وتقدّم","ألعاب قصيرة مصممة لتنمية المهارات ومنحك نقاطًا إضافية.")}
<div class="content-grid">${games.map((g,i)=>`<article class="content-card"><div class="card-visual ${g[3]}">${g[2]}</div><div class="card-body"><h3>${g[0]}</h3><p>${g[1]}</p><div class="card-meta"><span>أفضل نتيجة: ${g[4]*8}</span><button class="card-action" onclick="playGame(${i})">العب الآن ←</button></div></div></article>`).join("")}</div>`}

async function renderStore(){try{const rewardsData=await api("rewards");state.rewards=rewardsData.rewards}catch(error){return showToast(error.message)}document.querySelector("#storePage").innerHTML=`
${pageBanner("متجر الجوائز","استبدل نقاطك بجوائز يومية وأسبوعية وكبرى.")}
<section class="reward-balance"><div><small>رصيدك الحالي</small><strong><span>★</span> ${state.points.toLocaleString("ar-SA")} نقطة</strong></div><button class="primary-button" onclick="navigate('competitions')">اجمع نقاطًا أكثر</button></section>
<div class="reward-store">${rewardSections()}</div>`}

function renderPosts(){document.querySelector("#postsPage").innerHTML=`
${pageBanner("ساحة أصدقاء صيف","تابع الأخبار وشارك أصدقاءك إنجازاتك وأفكارك المرحة.")}
<div class="post-composer"><textarea id="postText" placeholder="شارك إنجازًا أو فكرة مع أصدقاء صيف..."></textarea><div class="composer-footer"><button class="primary-button" onclick="publishPost()">نشر المشاركة</button></div></div>
<div>${state.posts.map(post=>`<article class="post-card"><div class="post-head"><div class="avatar">${post.author[0]}</div><div><strong>${post.author}</strong><time>${post.role} · ${post.time}</time></div></div><p>${post.text}</p><div class="post-actions"><button onclick="likePost(${post.id})">♡ ${post.likes} إعجاب</button><button>◌ تعليق</button><button>↗ مشاركة</button></div></article>`).join("")}</div>`}

async function renderOwner(section="overview"){if(currentUser?.role!=="owner")return navigate("home");try{const [usersData,requestsData,rewardsData,ordersData,achievementData,challengeData,competitionData]=await Promise.all([api("owner/users"),api("owner/registration-requests"),api("rewards"),api("owner/reward-orders"),api("owner/achievement-tasks"),api("owner/daily-challenge-settings"),api("owner/competition-settings")]);authData.users=usersData.users;authData.requests=requestsData.requests;state.rewards=rewardsData.rewards;state.rewardOrders=ordersData.orders;state.achievementTasks=achievementData.tasks;state.challengeSettings=challengeData.settings;state.competitionSettings=competitionData.settings}catch(error){showToast(error.message);return}const pendingOrders=state.rewardOrders.filter(order=>order.status==="pending").length;const tabs=[["overview","نظرة عامة"],["challenges","نقاط المسابقات والتحديات"],["achievements","مهام الإنجازات"],["rewards","متجر الجوائز"],["rewardOrders",`طلبات الجوائز (${pendingOrders})`],["requests",`طلبات التسجيل (${authData.requests.length})`],["students","المستفيدون"],["content","المحتوى والبرامج"]];const action=section==="achievements"?`<button class="primary-button" onclick="openAchievementTaskForm()">+ مهمة يومية</button>`:section==="rewards"?`<button class="primary-button" onclick="openRewardForm()">+ جائزة جديدة</button>`:section==="students"?`<button class="primary-button" onclick="openAddUser()">+ إضافة مستفيد</button>`:"";document.querySelector("#ownerPage").innerHTML=`
${pageBanner("مرحبًا بك في مركز التحكم","أدر الحسابات وطلبات التسجيل والمحتوى والمتجر من مكان واحد.",action)}
<div class="owner-layout"><div>${ownerSection(section)}</div><nav class="owner-nav">${tabs.map(t=>`<button class="owner-tab ${section===t[0]?"active":""}" onclick="renderOwner('${t[0]}')">${t[1]}</button>`).join("")}</nav></div>`}
function ownerSection(section){
if(section==="challenges")return`<div class="owner-panel challenge-points-panel"><div class="panel-title"><div><h3>نقاط المسابقات والتحديات</h3><p>حدد المكافأة لكل مسابقة والحد الأعلى لنقاط كل تحدٍ يومي.</p></div><span class="owner-challenge-symbol">✦</span></div><h4 class="points-section-title">🏆 نقاط المسابقات</h4><div class="challenge-points-grid competition-points-grid">${competitions.map(item=>{const setting=(state.competitionSettings||[]).find(row=>Number(row.competition_id)===item.id);return`<label class="challenge-point-row"><span>${item.icon}</span><div><strong>${item.title}</strong><small>مكافأة إكمال المسابقة</small></div><input id="competitionPoints-${item.id}" type="number" min="1" max="10000" value="${Number(setting?.points||item.reward)}"><button onclick="saveCompetitionPoints(${item.id})">حفظ</button></label>`}).join("")}</div><h4 class="points-section-title">✦ نقاط التحديات اليومية</h4><div class="challenge-points-grid">${dailyChallengeCatalog.map(([key,name,icon])=>{const setting=(state.challengeSettings||[]).find(item=>item.challenge_key===key);return`<label class="challenge-point-row"><span>${icon}</span><div><strong>${name}</strong><small>الحد الأعلى للنقاط</small></div><input id="challengePoints-${key}" type="number" min="1" max="10000" value="${Number(setting?.max_points||100)}"><button onclick="saveChallengePoints('${key}')">حفظ</button></label>`}).join("")}</div></div>`;
if(section==="achievements")return`<div class="owner-panel"><div class="panel-title"><div><h3>مهام الإنجازات اليومية</h3><p>أضف المهمة ودرجتها مرة واحدة، وستظهر للمستفيدين يوميًا تلقائيًا.</p></div></div>${(state.achievementTasks||[]).length?`<div class="table-scroll"><table class="data-table"><thead><tr><th>المهمة</th><th>القسم</th><th>النقاط</th><th>منذ</th><th>الحالة</th></tr></thead><tbody>${state.achievementTasks.map(task=>`<tr><td><strong>${escapeHtml(task.title)}</strong>${task.description?`<small class="table-subtext">${escapeHtml(task.description)}</small>`:""}</td><td>${achievementCategories[task.category]?.icon||""} ${achievementCategories[task.category]?.name||task.category}</td><td>${Number(task.points).toLocaleString("ar-SA")}</td><td>${new Date(`${task.start_date}T12:00:00`).toLocaleDateString("ar-SA")}</td><td><button class="${task.active?"deliver-button":"edit-button"}" onclick="toggleAchievementTask(${task.id},${task.active?"false":"true"})">${task.active?"نشطة · إيقاف":"متوقفة · تفعيل"}</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">لا توجد مهام بعد. أضف أول مهمة يومية.</div>`}</div>`;
if(section==="rewards")return`<div class="owner-panel"><div class="panel-title"><div><h3>متجر الجوائز</h3><p>إدارة الجوائز اليومية والأسبوعية والكبرى</p></div></div>${(state.rewards||[]).length?`<div class="table-scroll"><table class="data-table rewards-table"><thead><tr><th>الصورة</th><th>اسم الجائزة</th><th>التكلفة</th><th>التصنيف</th><th>الإجراءات</th></tr></thead><tbody>${state.rewards.map(reward=>`<tr><td><img class="reward-thumb" src="${reward.image}" alt=""></td><td><strong>${escapeHtml(reward.name)}</strong></td><td>${formatRewardPoints(reward.amount)}</td><td><span class="category-badge category-${reward.category}">${rewardCategoryLabels[reward.category]}</span></td><td><div class="table-actions"><button class="edit-button" onclick="openRewardForm(${reward.id})">تعديل</button><button class="delete-button" onclick="removeReward(${reward.id})">حذف</button></div></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">لا توجد جوائز بعد. أضف أول جائزة من الزر أعلاه.</div>`}</div>`;
if(section==="rewardOrders")return`<div class="owner-panel"><div class="panel-title"><div><h3>طلبات الجوائز</h3><p>طلبات المستفيدين مرتبة من الأحدث</p></div></div>${(state.rewardOrders||[]).length?`<div class="table-scroll"><table class="data-table rewards-table"><thead><tr><th>الجائزة</th><th>المستفيد</th><th>النقاط</th><th>التاريخ</th><th>الحالة</th></tr></thead><tbody>${state.rewardOrders.map(order=>`<tr><td><div class="order-reward"><img class="reward-thumb" src="${order.reward_image}" alt=""><strong>${escapeHtml(order.reward_name)}</strong></div></td><td>${escapeHtml(order.user_name)}<small class="table-subtext">@${escapeHtml(order.username)}</small></td><td>${formatRewardPoints(order.points_paid)}</td><td>${new Date(order.created_at).toLocaleDateString("ar-SA")}</td><td>${order.status==="pending"?`<button class="deliver-button" onclick="markOrderDelivered(${order.id})">تأكيد التسليم</button>`:`<span class="delivered-badge">تم التسليم</span>`}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">لا توجد طلبات جوائز حتى الآن</div>`}</div>`;
if(section==="requests"){const requests=authData.requests.filter(r=>r.status==="pending");return`<div class="owner-panel"><h3>طلبات التسجيل الجديدة</h3>${requests.length?requests.map(r=>`<article class="request-card"><div><strong>${r.name}</strong><p>اسم المستخدم: ${r.username} · التواصل: ${r.contact}</p>${r.note?`<p>${r.note}</p>`:""}</div><div class="request-actions"><button class="small-button" onclick="approveRequest(${r.id})">قبول</button><button class="small-button reject" onclick="rejectRequest(${r.id})">رفض</button></div></article>`).join(""):`<div class="empty-state">لا توجد طلبات تسجيل جديدة</div>`}</div>`}
if(section==="products")return`<div class="owner-panel"><h3>منتجات المتجر</h3><table class="data-table"><thead><tr><th>المنتج</th><th>السعر</th><th>المخزون</th><th></th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${p.icon} ${p.name}</td><td>${p.price} نقطة</td><td>${p.stock}</td><td><button class="card-action" onclick="deleteProduct(${p.id})">حذف</button></td></tr>`).join("")}</tbody></table></div>`;
if(section==="content")return`<div class="owner-panel"><h3>المحتوى المنشور</h3><table class="data-table"><thead><tr><th>القسم</th><th>عدد العناصر</th><th>الحالة</th></tr></thead><tbody><tr><td>المسابقات</td><td>6</td><td>نشط</td></tr><tr><td>الحلقات والبرامج</td><td>24</td><td>نشط</td></tr><tr><td>التحديات اليومية</td><td>10</td><td>نشط</td></tr></tbody></table></div>`;
if(section==="students"){const users=authData.users.filter(u=>u.role==="student");return`<div class="owner-panel"><h3>حسابات المستفيدين</h3>${users.length?`<table class="data-table"><thead><tr><th>المستفيد</th><th>اسم المستخدم</th><th>المستوى</th><th>النقاط</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.name}</td><td>${u.username}</td><td>${u.level}</td><td>${Number(u.points||0).toLocaleString("ar-SA")}</td><td><button class="card-action" onclick="deleteUser('${u.id}')">حذف</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty-state">لم تتم إضافة مستفيدين بعد</div>`}</div>`}
return`<div class="stat-grid"><div class="stat-card"><strong>${authData.users.filter(u=>u.role==="student").length}</strong><span>مستفيد نشط</span></div><div class="stat-card"><strong>${authData.requests.filter(r=>r.status==="pending").length}</strong><span>طلب تسجيل جديد</span></div><div class="stat-card"><strong>24</strong><span>حلقة منشورة</span></div><div class="stat-card"><strong>${state.products.length}</strong><span>منتجات المتجر</span></div></div><div class="owner-panel"><h3>إدارة سريعة</h3><p>راجع طلبات التسجيل، أضف المستفيدين، ثم تابع نقاطهم وإنجازاتهم من لوحة واحدة.</p></div>`}

function openModal(content){document.querySelector("#modalContent").innerHTML=content;document.querySelector("#modalBackdrop").classList.add("open")}
function closeModal(){document.querySelector("#modalBackdrop").classList.remove("open")}
function showToast(text){const toast=document.querySelector("#toast");toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
async function saveChallengePoints(key){const input=document.querySelector(`#challengePoints-${key}`),maxPoints=Number(input?.value);try{await api(`owner/daily-challenge-settings/${key}`,{method:"PUT",body:JSON.stringify({maxPoints})});const setting=(state.challengeSettings||[]).find(item=>item.challenge_key===key);if(setting)setting.max_points=maxPoints;showToast("تم حفظ نقاط التحدي")}catch(error){showToast(error.message)}}
async function saveCompetitionPoints(id){const input=document.querySelector(`#competitionPoints-${id}`),points=Number(input?.value);try{await api(`owner/competition-settings/${id}`,{method:"PUT",body:JSON.stringify({points})});const setting=(state.competitionSettings||[]).find(item=>Number(item.competition_id)===id);if(setting)setting.points=points;const competition=competitions.find(item=>item.id===id);if(competition)competition.reward=points;showToast("تم حفظ نقاط المسابقة")}catch(error){showToast(error.message)}}
function showStage(stage){const data={1:["بداية الرحلة","أكملت جميع المهام الأساسية وحصلت على شارة الانطلاق.","مكتملة"],2:["حديقة المعرفة","أنهيت 7 أنشطة في القراءة والحساب وجمعت 820 نقطة.","مكتملة"],3:["مرصد العلوم","أكمل نشاطين إضافيين لفتح تحدي الفضاء والحصول على 300 نقطة.","قيد التقدم"],4:["جزيرة الإبداع","تفتح بعد إكمال 80% من مرصد العلوم.","مغلقة"]};openModal(`<h2>${data[stage][0]}</h2><p>${data[stage][1]}</p><span class="status-badge" style="background:#e8f5f1">${data[stage][2]}</span><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إغلاق</button></div>`)}
function openCompetition(id){if(state.completedCompetitions.includes(id))return showToast("أكملت هذه المسابقة بالفعل");const comp=competitions.find(c=>c.id===id);openModal(`<span class="eyebrow">السؤال 1 من 3</span><h2>${comp.title}</h2><p>ما الكوكب المعروف بالكوكب الأحمر؟</p><div class="quiz-options"><button class="quiz-option" onclick="finishCompetition(${id},${comp.reward},false)">الزهرة</button><button class="quiz-option" onclick="finishCompetition(${id},${comp.reward},true)">المريخ</button><button class="quiz-option" onclick="finishCompetition(${id},${comp.reward},false)">المشتري</button></div><button class="outline-button" onclick="closeModal()">إنهاء لاحقًا</button>`)}
async function finishCompetition(id,reward,correct){if(!correct)return showToast("إجابة قريبة، جرّب مرة أخرى");try{const result=await api("progress/award",{method:"POST",body:JSON.stringify({type:"competition",id})});state.points=result.points;currentUser.points=result.points;state.completedCompetitions.push(id);saveState();closeModal();renderCompetitions();showToast(`أحسنت! ربحت ${result.awarded} نقطة`)}catch(error){showToast(error.message)}}
function playEpisode(index){openModal(`<div class="card-visual ${episodes[index][4]}" style="border-radius:6px">${episodes[index][3]}</div><h2>${episodes[index][1]}</h2><p>سيظهر مشغل الحلقة التعليمية هنا، مع سؤال قصير بعد المشاهدة.</p><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إغلاق</button><button class="primary-button" onclick="closeModal();showToast('تمت إضافة الحلقة إلى قائمة المتابعة')">أضف للمتابعة</button></div>`)}
function playGame(index){const game=games[index];openModal(`<h2>${game[0]}</h2><div class="daily-icon">${game[2]}</div><p>${game[1]}</p><div class="modal-actions"><button class="outline-button" onclick="closeModal()">لاحقًا</button><button class="primary-button" onclick="awardGame(${index})">ابدأ جولة سريعة</button></div>`)}
async function awardGame(index){try{const result=await api("progress/award",{method:"POST",body:JSON.stringify({type:"game",id:index})});state.points=result.points;currentUser.points=result.points;saveState();closeModal();showToast(`رائع! أضفنا ${result.awarded} نقطة إلى رصيدك`)}catch(error){showToast(error.message)}}
function buyProduct(id){const product=state.products.find(p=>p.id===id);if(!product||product.stock<1||state.points<product.price)return showToast("رصيدك لا يكفي لشراء هذا المنتج");openModal(`<h2>تأكيد الشراء</h2><div class="daily-icon">${product.icon}</div><p>هل تريد شراء <strong>${product.name}</strong> مقابل ${product.price.toLocaleString("ar-SA")} نقطة؟</p><div class="modal-actions"><button class="outline-button" onclick="closeModal()">تراجع</button><button class="primary-button" onclick="confirmPurchase(${id})">تأكيد الشراء</button></div>`)}
async function confirmPurchase(id){try{const result=await api("store/purchase",{method:"POST",body:JSON.stringify({productId:id})});state.points=result.points;currentUser.points=result.points;state.purchased.push({productId:id,date:new Date().toISOString()});saveState();closeModal();await renderStore();showToast("تم الشراء بنجاح، مبارك عليك المكافأة!")}catch(error){showToast(error.message)}}
function publishPost(){const input=document.querySelector("#postText");if(!input.value.trim())return showToast("اكتب شيئًا قبل النشر");state.posts.unshift({id:Date.now(),author:currentUser.name,role:currentUser.role==="owner"?"مالك المنصة":`مستفيد · المستوى ${currentUser.level||1}`,time:"الآن",text:input.value.trim(),likes:0});saveState();renderPosts();showToast("تم نشر مشاركتك")}
function likePost(id){const post=state.posts.find(p=>p.id===id);post.likes+=1;saveState();renderPosts()}
function openAchievementTaskForm(){if(currentUser?.role!=="owner")return;openModal(`<h2>إضافة مهمة إنجاز يومية</h2><p>تُضاف المهمة مرة واحدة، ثم تتجدد تلقائيًا كل يوم لجميع المستفيدين.</p><div class="form-grid"><div class="form-field full"><label>اسم المهمة</label><input id="achievementTaskTitle" maxlength="100" placeholder="مثال: أذكار الصباح"></div><div class="form-field"><label>القسم</label><select id="achievementTaskCategory">${Object.entries(achievementCategories).map(([key,item])=>`<option value="${key}">${item.icon} ${item.name}</option>`).join("")}</select></div><div class="form-field"><label>الدرجة اليومية</label><input id="achievementTaskPoints" type="number" min="1" max="10000" value="10"></div><div class="form-field full"><label>وصف مختصر (اختياري)</label><textarea id="achievementTaskDescription" maxlength="300" placeholder="تفاصيل تساعد المستفيد على إتمام المهمة"></textarea></div></div><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إلغاء</button><button class="primary-button" onclick="saveAchievementTask()">إضافة المهمة</button></div>`)}
async function saveAchievementTask(){const payload={title:document.querySelector("#achievementTaskTitle").value.trim(),description:document.querySelector("#achievementTaskDescription").value.trim(),category:document.querySelector("#achievementTaskCategory").value,points:Number(document.querySelector("#achievementTaskPoints").value)};try{await api("owner/achievement-tasks",{method:"POST",body:JSON.stringify(payload)});closeModal();await renderOwner("achievements");showToast("تمت إضافة المهمة وستظهر يوميًا للمستفيدين")}catch(error){showToast(error.message)}}
async function toggleAchievementTask(id,active){try{await api(`owner/achievement-tasks/${id}`,{method:"PUT",body:JSON.stringify({active})});await renderOwner("achievements");showToast(active?"تم تفعيل المهمة":"تم إيقاف المهمة مع حفظ السجل السابق")}catch(error){showToast(error.message)}}
function openAddUser(){openModal(`<h2>إضافة مستفيد</h2><div class="form-grid"><div class="form-field full"><label>الاسم الكامل</label><input id="newUserName" placeholder="اسم المستفيد"></div><div class="form-field"><label>اسم المستخدم</label><input id="newUsername" placeholder="username"></div><div class="form-field"><label>كلمة المرور</label><input id="newUserPassword" type="password" placeholder="8 أحرف على الأقل"></div><div class="form-field"><label>المستوى</label><input id="newUserLevel" type="number" min="1" value="1"></div><div class="form-field"><label>النقاط الابتدائية</label><input id="newUserPoints" type="number" min="0" value="0"></div></div><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إلغاء</button><button class="primary-button" onclick="addUser()">إنشاء الحساب</button></div>`)}
async function addUser(){const payload={name:document.querySelector("#newUserName").value.trim(),username:document.querySelector("#newUsername").value.trim(),password:document.querySelector("#newUserPassword").value,level:Number(document.querySelector("#newUserLevel").value)||1,points:Number(document.querySelector("#newUserPoints").value)||0};try{await api("owner/users",{method:"POST",body:JSON.stringify(payload)});closeModal();await renderOwner("students");showToast("تم إنشاء حساب المستفيد")}catch(error){showToast(error.message)}}
function approveRequest(id){const request=authData.requests.find(r=>r.id===id);if(!request)return;openModal(`<h2>قبول طلب ${request.name}</h2><p>حدد كلمة المرور الأولية وأرسلها إلى المستفيد.</p><div class="form-grid"><div class="form-field full"><label>اسم المستخدم</label><input id="approvedUsername" value="${request.username}"></div><div class="form-field"><label>كلمة المرور الأولية</label><input id="approvedPassword" value="Seif${String(id).slice(-4)}"></div><div class="form-field"><label>المستوى</label><input id="approvedLevel" type="number" min="1" value="1"></div></div><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إلغاء</button><button class="primary-button" onclick="confirmApproval(${id})">اعتماد الحساب</button></div>`)}
async function confirmApproval(id){const username=document.querySelector("#approvedUsername").value.trim();const password=document.querySelector("#approvedPassword").value;try{await api(`owner/registration-requests/${id}/approve`,{method:"POST",body:JSON.stringify({username,password,level:Number(document.querySelector("#approvedLevel").value)||1})});closeModal();await renderOwner("requests");showToast(`تم اعتماد الحساب، كلمة المرور: ${password}`)}catch(error){showToast(error.message)}}
async function rejectRequest(id){try{await api(`owner/registration-requests/${id}/reject`,{method:"POST"});await renderOwner("requests");showToast("تم رفض الطلب")}catch(error){showToast(error.message)}}
async function deleteUser(id){try{await api(`owner/users/${id}`,{method:"DELETE"});await renderOwner("students");showToast("تم حذف حساب المستفيد")}catch(error){showToast(error.message)}}
function buyReward(id){const reward=(state.rewards||[]).find(item=>item.id===id);if(!reward||currentUser?.role!=="student")return;if(state.points<Number(reward.amount))return showToast("رصيدك لا يكفي لشراء هذه الجائزة");openModal(`<h2>تأكيد شراء الجائزة</h2><div class="purchase-reward-preview"><img src="${reward.image}" alt=""><div><strong>${escapeHtml(reward.name)}</strong><span>${formatRewardPoints(reward.amount)}</span></div></div><p>سيتم خصم النقاط من رصيدك وإرسال الطلب إلى مالك المنصة.</p><div class="modal-actions"><button class="outline-button" onclick="closeModal()">تراجع</button><button class="primary-button" onclick="confirmRewardPurchase(${id})">تأكيد الشراء</button></div>`)}
async function confirmRewardPurchase(id){try{const result=await api(`rewards/${id}/purchase`,{method:"POST"});state.points=result.points;currentUser.points=result.points;updatePoints();closeModal();await renderStore();showToast("ستصلك الجائزة قريبًا")}catch(error){showToast(error.message)}}
async function markOrderDelivered(id){if(currentUser?.role!=="owner")return;try{await api(`owner/reward-orders/${id}/delivered`,{method:"PUT"});await renderOwner("rewardOrders");showToast("تم تأكيد تسليم الجائزة")}catch(error){showToast(error.message)}}
function openRewardForm(id=null){if(currentUser?.role!=="owner")return showToast("هذه الصفحة مخصصة للمالك");const reward=id?(state.rewards||[]).find(item=>item.id===id):null;openModal(`<h2>${reward?"تعديل الجائزة":"إضافة جائزة جديدة"}</h2><div class="reward-form"><div class="reward-upload"><img id="rewardPreview" src="${reward?.image||""}" alt="معاينة الجائزة" class="${reward?.image?"":"hidden"}"><div id="rewardPlaceholder" class="reward-placeholder ${reward?.image?"hidden":""}">🎁<small>صورة الجائزة</small></div><label class="upload-button">اختيار صورة<input id="rewardImage" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><small>PNG أو JPG أو WebP، بحد أقصى 650 كيلوبايت</small></div><div class="form-grid reward-fields"><div class="form-field full"><label>اسم الجائزة</label><input id="rewardName" maxlength="100" value="${escapeHtml(reward?.name||"")}" placeholder="مثال: قسيمة ألعاب"></div><div class="form-field"><label>تكلفة الجائزة بالنقاط</label><input id="rewardAmount" type="number" min="1" step="1" value="${reward?.amount||""}" placeholder="100"></div><div class="form-field"><label>تصنيف الجائزة</label><select id="rewardCategory"><option value="daily" ${reward?.category==="daily"?"selected":""}>جوائز يومية</option><option value="weekly" ${reward?.category==="weekly"?"selected":""}>جوائز أسبوعية</option><option value="grand" ${reward?.category==="grand"?"selected":""}>جوائز كبرى</option></select></div></div></div><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إلغاء</button><button class="primary-button" onclick="saveReward(${id||"null"})">${reward?"حفظ التعديلات":"إضافة الجائزة"}</button></div>`);document.querySelector("#rewardImage").addEventListener("change",previewRewardImage)}
function previewRewardImage(event){const file=event.target.files[0];if(!file)return;if(file.size>650*1024){event.target.value="";return showToast("حجم الصورة أكبر من 650 كيلوبايت")}const reader=new FileReader();reader.onload=()=>{const preview=document.querySelector("#rewardPreview");preview.src=reader.result;preview.classList.remove("hidden");document.querySelector("#rewardPlaceholder").classList.add("hidden")};reader.readAsDataURL(file)}
function fileAsDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");if(file.size>650*1024)return reject(new Error("حجم الصورة أكبر من 650 كيلوبايت"));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("تعذر قراءة الصورة"));reader.readAsDataURL(file)})}
async function saveReward(id){if(currentUser?.role!=="owner")return;const existing=id?(state.rewards||[]).find(item=>item.id===id):null;try{const uploaded=await fileAsDataUrl(document.querySelector("#rewardImage").files[0]);const payload={name:document.querySelector("#rewardName").value.trim(),amount:Number(document.querySelector("#rewardAmount").value),category:document.querySelector("#rewardCategory").value,image:uploaded||existing?.image||""};await api(id?`owner/rewards/${id}`:"owner/rewards",{method:id?"PUT":"POST",body:JSON.stringify(payload)});closeModal();await renderOwner("rewards");showToast(id?"تم تحديث الجائزة":"تمت إضافة الجائزة")}catch(error){showToast(error.message)}}
function removeReward(id){const reward=(state.rewards||[]).find(item=>item.id===id);if(!reward)return;openModal(`<h2>حذف الجائزة</h2><p>هل تريد حذف <strong>${escapeHtml(reward.name)}</strong>؟ لن تظهر بعد ذلك في المتجر.</p><div class="modal-actions"><button class="outline-button" onclick="closeModal()">تراجع</button><button class="danger-button" onclick="confirmRemoveReward(${id})">حذف الجائزة</button></div>`)}
async function confirmRemoveReward(id){if(currentUser?.role!=="owner")return;try{await api(`owner/rewards/${id}`,{method:"DELETE"});closeModal();await renderOwner("rewards");showToast("تم حذف الجائزة")}catch(error){showToast(error.message)}}
function openAddProduct(){openModal(`<h2>إضافة منتج جديد</h2><div class="form-grid"><div class="form-field full"><label>اسم المنتج</label><input id="productName" placeholder="مثال: قسيمة مقهى"></div><div class="form-field"><label>السعر بالنقاط</label><input id="productPrice" type="number" min="1" value="1000"></div><div class="form-field"><label>الكمية</label><input id="productStock" type="number" min="1" value="5"></div><div class="form-field"><label>رمز المنتج</label><input id="productIcon" value="🎁"></div><div class="form-field full"><label>الوصف</label><textarea id="productDesc" placeholder="وصف قصير للمنتج"></textarea></div></div><div class="modal-actions"><button class="outline-button" onclick="closeModal()">إلغاء</button><button class="primary-button" onclick="addProduct()">إضافة المنتج</button></div>`)}
async function addProduct(){const payload={name:document.querySelector("#productName").value.trim(),price:Number(document.querySelector("#productPrice").value),stock:Number(document.querySelector("#productStock").value),icon:document.querySelector("#productIcon").value||"🎁",description:document.querySelector("#productDesc").value||"مكافأة مميزة من دكان صيف"};try{await api("owner/products",{method:"POST",body:JSON.stringify(payload)});closeModal();await renderOwner("products");showToast("تمت إضافة المنتج إلى المتجر")}catch(error){showToast(error.message)}}
async function deleteProduct(id){try{await api(`owner/products/${id}`,{method:"DELETE"});await renderOwner("products");showToast("تم حذف المنتج")}catch(error){showToast(error.message)}}

document.addEventListener("click",event=>{const trigger=event.target.closest("[data-page]");if(trigger)navigate(trigger.dataset.page);if(event.target.id==="modalBackdrop")closeModal()});
document.querySelectorAll("[data-auth-view]").forEach(tab=>tab.addEventListener("click",()=>switchAuthView(tab.dataset.authView)));
document.querySelector("#loginForm").addEventListener("submit",async event=>{event.preventDefault();const message=document.querySelector("#loginMessage");message.textContent="جارٍ تسجيل الدخول...";try{await login(document.querySelector("#loginUsername").value,document.querySelector("#loginPassword").value);message.textContent=""}catch(error){message.textContent=error.message;message.classList.remove("success")}});
document.querySelector("#requestForm").addEventListener("submit",event=>{event.preventDefault();submitRegistration()});
document.querySelector("#logoutButton").addEventListener("click",logout);
document.querySelector("#menuButton").addEventListener("click",()=>document.querySelector("#sidebar").classList.toggle("open"));
document.querySelector("#startChallenge").addEventListener("click",()=>openCompetition(1));
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
(async function restoreSession(){try{const data=await api("auth/me");currentUser=data.user;showApp()}catch{document.querySelector("#authScreen").classList.remove("hidden")}})();
